### ISSUE TITLE
Questions to ask

### ISSUE THREAD

**Issue by jlin47** [jlin47/mp4#1]

**Comment by jlin47** [comment]
make a graph of male Vs. female actors. What kind of movies do they perform in?
Among movies that show more female/male character/producers/writer, which has more revenue?

**Comment by dasom1348** [comment]
The success of a movie depending on producers by gender:

- Two datasets about movie group by producer's gender 
- Two datasets about revenue of the movies 
- Graphs to visualize results

**Comment by jlin47** [comment]
#GET THE INFO FOR FEMALE PRODUCERS
SELECT n.name, ci.role_id, person_id
FROM cast_info ci
JOIN name n ON n.id = ci.person_id
WHERE role_id = "8" 
AND gender = "f"

**Comment by dasom1348** [comment]
role_type id -> 3: producer, 4: writer, 8: director 
kind_id-> movie, tv series or not
movie_id -> a specific movie 
get info movie, role_type id =8 and then join together

**Comment by dasom1348** [comment]
+1 for using precise SQL queries (i.e. requesting only the columns you need, rather than requesting everything and filtering in R)

I think we don't need production year column in our sql! we can remove it!

**Comment by dasom1348** [comment]
select movie_id from cast_info and then join by matching movie id in the best_movie table
